### ISSUE TITLE
Tracking issue for landing page

### ISSUE THREAD

**Issue by Karrrramba** [Karrrramba/Titanic#1]
- [x] EDA
- [x] Add variable plots
- [x] Add correlation map
- [x] Add composite plots of variables distributions
- [x] Remove columns
- [x] Impute missing values
- [ ] FE
- [ ] Transform fare
- [ ] Scaling for LogReg model
- [ ] Create interaction terms
- [ ] Multicollinearity/Feature importance
- [ ] Modeling
- [ ] Build basic model
- [ ] Hyperparameter tuning
